$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_pso_01_5_1.txt > ./irace/result/output_pso_01_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_pso_06_5_1.txt > ./irace/result/output_pso_06_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_pso_10_5_1.txt > ./irace/result/output_pso_10_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_pso_16_5_1.txt > ./irace/result/output_pso_16_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_pso_23_5_1.txt > ./irace/result/output_pso_23_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_ata_01_5_1.txt > ./irace/result/output_ata_01_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_ata_06_5_1.txt > ./irace/result/output_ata_06_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_ata_10_5_1.txt > ./irace/result/output_ata_10_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_ata_16_5_1.txt > ./irace/result/output_ata_16_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_ata_23_5_1.txt > ./irace/result/output_ata_23_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_gsa_01_5_1.txt > ./irace/result/output_gsa_01_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_gsa_06_5_1.txt > ./irace/result/output_gsa_06_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_gsa_10_5_1.txt > ./irace/result/output_gsa_10_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_gsa_16_5_1.txt > ./irace/result/output_gsa_16_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_gsa_23_5_1.txt > ./irace/result/output_gsa_23_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_ffa_01_5_1.txt > ./irace/result/output_ffa_01_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_ffa_06_5_1.txt > ./irace/result/output_ffa_06_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_ffa_10_5_1.txt > ./irace/result/output_ffa_10_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_ffa_16_5_1.txt > ./irace/result/output_ffa_16_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_ffa_23_5_1.txt > ./irace/result/output_ffa_23_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_rio_01_5_1.txt > ./irace/result/output_rio_01_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_rio_06_5_1.txt > ./irace/result/output_rio_06_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_rio_10_5_1.txt > ./irace/result/output_rio_10_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_rio_16_5_1.txt > ./irace/result/output_rio_16_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_rio_23_5_1.txt > ./irace/result/output_rio_23_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_de_01_5_1.txt > ./irace/result/output_de_01_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_de_06_5_1.txt > ./irace/result/output_de_06_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_de_10_5_1.txt > ./irace/result/output_de_10_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_de_16_5_1.txt > ./irace/result/output_de_16_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_de_23_5_1.txt > ./irace/result/output_de_23_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_saa_01_5_1.txt > ./irace/result/output_saa_01_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_saa_06_5_1.txt > ./irace/result/output_saa_06_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_saa_10_5_1.txt > ./irace/result/output_saa_10_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_saa_16_5_1.txt > ./irace/result/output_saa_16_5_1.txt
$Rscript /usr/local/lib/R/site-library/irace/bin/irace -s ./irace/scenario_saa_23_5_1.txt > ./irace/result/output_saa_23_5_1.txt
